server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/polling?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: qweasdzxc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

app:
  jwt:
    secret: JwtSecretKey
    expiration: 60480000